# Generated by Django 5.0.6 on 2025-05-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProjet', models.CharField(help_text='Entrez le nom du projet', max_length=255, verbose_name='Nom du projet')),
                ('description', models.TextField(help_text='Description détaillée du projet', verbose_name='Description')),
                ('categorie', models.CharField(choices=[('DEV_WEB', 'Développement web'), ('DEV_MOBILE', 'Développement mobile'), ('CYBERSECURITE', 'Cybersécurité'), ('RESEAU_INFRA', 'Réseau et Infrastructure'), ('IA', 'Intelligence Artificielle')], help_text='Sélectionnez la catégorie du projet', max_length=20, verbose_name='Catégorie')),
                ('client', models.CharField(blank=True, help_text='Nom du client (optionnel)', max_length=255, null=True, verbose_name='Client')),
                ('dateDebut', models.DateField(help_text='Date de début du projet', verbose_name='Date de début')),
                ('dateFin', models.DateField(blank=True, help_text='Date de fin du projet (optionnel)', null=True, verbose_name='Date de fin')),
                ('mission', models.TextField(help_text='Décrivez la mission du projet', verbose_name='Mission')),
                ('challenge', models.TextField(blank=True, help_text='Décrivez les défis rencontrés', null=True, verbose_name='Challenge')),
                ('solution', models.TextField(blank=True, help_text='Décrivez les solutions apportées', null=True, verbose_name='Solution')),
                ('resultat', models.TextField(blank=True, help_text='Décrivez les résultats obtenus', null=True, verbose_name='Résultat')),
                ('image1', models.ImageField(blank=True, help_text="Téléchargez l'image principale", null=True, upload_to='realisations/', verbose_name='Image principale')),
                ('image2', models.ImageField(blank=True, help_text='Téléchargez une image secondaire', null=True, upload_to='realisations/', verbose_name='Image secondaire 1')),
                ('image3', models.ImageField(blank=True, help_text='Téléchargez une autre image secondaire', null=True, upload_to='realisations/', verbose_name='Image secondaire 2')),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations',
                'ordering': ['-dateDebut'],
            },
        ),
    ]
