# Generated by Django 5.1.7 on 2025-06-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        help_text="Titre du service",
                        max_length=255,
                        verbose_name="Titre",
                    ),
                ),
                (
                    "sous_titre",
                    models.CharField(
                        help_text="Sous-titre descriptif du service",
                        max_length=255,
                        verbose_name="Sous-titre",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image illustrant le service",
                        null=True,
                        upload_to="services/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description détaillée du service",
                        verbose_name="Description",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        default=list,
                        help_text="Liste de 3 détails avec spécificité et détail",
                        verbose_name="Détails",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ["titre"],
            },
        ),
    ]
