# Generated by Django 5.2 on 2025-05-12 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "utilisateurs",
                    models.ManyToManyField(
                        help_text="Comptes utilisateurs Django associés à ces administrateurs",
                        related_name="administrateurs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Comptes utilisateurs associés",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrateur",
                "verbose_name_plural": "Administrateurs",
            },
        ),
    ]
