# Generated by Django 5.2 on 2025-05-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = []
