# Generated by Django 5.1.7 on 2025-06-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom de famille de l'employé",
                        max_length=100,
                        verbose_name="Nom",
                    ),
                ),
                (
                    "prenom",
                    models.CharField(
                        help_text="Prénom de l'employé",
                        max_length=100,
                        verbose_name="Prénom",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo de profil de l'employé",
                        null=True,
                        upload_to="equipe/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "poste",
                    models.CharField(
                        help_text="Intitulé du poste de l'employé",
                        max_length=255,
                        verbose_name="Poste",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si l'employé est toujours dans l'équipe",
                        verbose_name="Actif",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employé",
                "verbose_name_plural": "Employés",
                "ordering": ["nom", "prenom"],
            },
        ),
    ]
