# Generated by Django 5.1.7 on 2025-06-08 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("partenaires", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partenaire",
            options={"ordering": ["nom"]},
        ),
    ]
