# Generated by Django 5.1.7 on 2025-06-08 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="demandestage",
            options={"ordering": ["-date_demande"]},
        ),
        migrations.AlterModelOptions(
            name="offrestage",
            options={"ordering": ["-date_debut"]},
        ),
    ]
